### ISSUE TITLE
arm64-v8a version of libyuv_static.a

### ISSUE THREAD

**Issue by meegoStar** [wangnamu/AICamera_new#2]
Hi, I am working on a **arm64-v8a** version of your great tutorial. Since the official Caffe2 AICamera project has not been updated for several months, this repo really helps me a lot.

My question is that how could I generate the `libyuv_static.a` for **arm64-v8a**? Should I compile it based on other project? Thanks!

**Comment by wangnamu** [comment]
Hi, @meegoStar  You can check https://chromium.googlesource.com/libyuv/libyuv/+/master

**Comment by meegoStar** [comment]
Hi, @wangnamu , thanks for your reply!

Based on the "Getting started" instructions in the link you provide, I build `libyuv_internal.a` and `libyuv_neon.a` for **arm64-v8a** successfully, and finally manage to make the **arm64-v8a** version of this AICamera project work!!! Great thanks again!

p.s. For any others interested in building `libyuv_*.a` for **arm64-v8a**, this link in the "Getting started" page (https://code.google.com/p/chromium/wiki/AndroidBuildInstructions) is outdated and should be changed to this one (https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md#install-additional-build-dependencies).

**Comment by wangnamu** [comment]
@meegoStar Fine, thank you
